version: "3.8"

services:
  app:
    build: .
    depends_on:
      - db
    networks:
      - edoc-net
    command: vendor/bin/phpunit tests

  db:
    image: mysql:5.7
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: edoc
      MYSQL_USER: root
      MYSQL_PASSWORD: root
    ports:
      - "3306:3306"
    networks:
      - edoc-net

networks:
  edoc-net:
